task/FCT2-21985 Add deployment gate to Prod pipeline (#115)

diff --git a/pipeline/templates/terragrunt_job.yml b/pipeline/templates/terragrunt_job.yml
--- a/pipeline/templates/terragrunt_job.yml
+++ b/pipeline/templates/terragrunt_job.yml
@@ -5,12 +5,15 @@ parameters:
     type: string
   - name: subscription
     type: string
+  - name: dependsOnJob
+    type: object
+    default: []
   - name: dependsOnTfModules
     type: object
     default: []
   - name: variableGroupName
     type: string
-    default: ''
+    default: ""
   - name: runApply
     type: boolean
     default: false
@@ -19,13 +22,13 @@ jobs:
   - job: terragrunt_${{parameters.module}}_${{parameters.environment}}
     displayName: ${{parameters.environment}}-${{parameters.module}}-terragrunt
     variables:
-      moduleDir: '$(System.DefaultWorkingDirectory)/environments/${{parameters.environment}}/${{parameters.module}}'
-      terraformVersion: '1.15.8'
-      terragruntVersion: '1.1.1'
-    ${{ if parameters.dependsOnTfModules }}:
-      dependsOn:
-        - ${{ each module in parameters.dependsOnTfModules }}:
-            - terragrunt_${{ module }}_${{parameters.environment}}
+      moduleDir: "$(System.DefaultWorkingDirectory)/environments/${{parameters.environment}}/${{parameters.module}}"
+      terraformVersion: "1.15.8"
+      terragruntVersion: "1.1.1"
+    dependsOn:
+      - ${{ parameters.dependsOnJob }}
+      - ${{ each module in parameters.dependsOnTfModules }}:
+          - terragrunt_${{ module }}_${{parameters.environment}}
 
     steps:
       - bash: |
@@ -69,8 +72,6 @@ jobs:
 
             rm -f "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
           }
-
-          install_terraform
 
           install_terraform
 
@@ -120,59 +121,63 @@ jobs:
             echo "##vso[task.setvariable variable=ARM_OIDC_TOKEN]$idToken"
             echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
 
-      - bash: |
-          echo "Configuring az devops cli..."
-          az devops configure --defaults organization='$(System.TeamFoundationCollectionUri)' project='$(System.TeamProject)' --use-git-aliases true
+      - ${{ if ne(parameters.variableGroupName, '') }}:
+          - bash: |
+              echo "Configuring az devops cli..."
+              az devops configure --defaults organization='$(System.TeamFoundationCollectionUri)' project='$(System.TeamProject)' --use-git-aliases true
 
-          echo "Retrieving variables from variable group ${{ parameters.variableGroupName }}..."
+              echo "Retrieving variables from variable group ${{ parameters.variableGroupName }}..."
 
-          # Get variable group id
-          variableGroupId="$(az pipelines variable-group list --group-name ${{ parameters.variableGroupName }} --query [].id -o tsv)"
+              # Get variable group id
+              variableGroupId="$(az pipelines variable-group list --group-name ${{ parameters.variableGroupName }} --query [].id -o tsv)"
 
-          VARS_FILE=terraform.tfvars.json
-          echo "Writing variables to $VARS_FILE..."
+              if [ -z $variableGroupId ]; then
+                echo "Variable group ${{ parameters.variableGroupName }} was not found."
+                exit 1
+              fi
 
-          # Write all variables in the group to a file
-          az pipelines variable-group variable list --group-id $variableGroupId > vars.json
+              VARS_FILE=terraform.tfvars.json
+              echo "Writing variables to $VARS_FILE..."
 
-          # Write tfvars file
-          jq 'map_values(.value)' vars.json > "$VARS_FILE"
+              # Write all variables in the group to a file
+              az pipelines variable-group variable list --group-id $variableGroupId > vars.json
 
-          if [ -f "$VARS_FILE" ]; then
-            echo "File $VARS_FILE has been written to $(moduleDir). It will be automatically consumed by terraform."
-            exit 0
-          else
-            echo "File $VARS_FILE not found."
-            exit 1
-          fi
-        displayName: 'Write tfvars file from variable group'
-        condition: ${{ ne(parameters.variableGroupName, '') }}
-        workingDirectory: $(moduleDir)
-        env:
-          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
+              # Write tfvars file
+              jq 'map_values(.value)' vars.json > "$VARS_FILE"
+
+              if [ -f "$VARS_FILE" ]; then
+                echo "File $VARS_FILE has been written to $(moduleDir). It will be automatically consumed by terraform."
+                exit 0
+              else
+                echo "File $VARS_FILE not found."
+                exit 1
+              fi
+            displayName: "Write tfvars file from variable group"
+            workingDirectory: $(moduleDir)
+            env:
+              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
 
       - bash: |
           PLAN_PATH='$(moduleDir)/tf.plan'
-          error_code=0
 
-          (terragrunt plan -out "$PLAN_PATH" --detailed-exitcode) || error_code=$?
+          (terragrunt plan -out $PLAN_PATH --detailed-exitcode) || error_code=$?
           if [[ "${error_code}" -eq 1 ]]; then
             exit 1
           elif [[ "${error_code}" -eq 2 ]]; then
             echo "##vso[task.logissue type=warning]Plan '${{parameters.module}}' has changes on ${{parameters.environment}}"
           fi
         displayName: "!!!! ${{parameters.environment}} Plan ${{parameters.module}} !!!!"
-        workingDirectory: $(System.DefaultWorkingDirectory)/environments/${{parameters.environment}}/${{parameters.module}}
-
-      - bash: |
-          PLAN_PATH='$(moduleDir)/tf.plan'
-          terragrunt apply "$PLAN_PATH"
-        condition: ${{ eq(parameters.runApply, true) }}
-        displayName: "!!! ${{parameters.environment}} Apply ${{parameters.module}} !!!"
         workingDirectory: $(moduleDir)
 
-      - bash: |
-          rm -f vars.json terraform.tfvars.json
-        condition:  ${{ ne(parameters.variableGroupName, '') }}
-        displayName: "Delete sensitive variable files"
-        workingDirectory: $(moduleDir)
+      - ${{ if eq(parameters.runApply, true) }}:
+          - bash: |
+              PLAN_PATH='$(moduleDir)/tf.plan'
+              terragrunt apply $PLAN_PATH
+            displayName: "!!! ${{parameters.environment}} Apply ${{parameters.module}} !!!"
+            workingDirectory: $(moduleDir)
+
+      - ${{ if ne(parameters.variableGroupName, '') }}:
+          - bash: |
+              rm -f vars.json terraform.tfvars.json
+            displayName: "Delete sensitive variable files"
+            workingDirectory: $(moduleDir)
